default_border pixel 2
default_floating_border pixel 2
hide_edge_borders smart

gaps inner 4
gaps outer 8

focus_follows_mouse yes
focus_on_window_activation smart
mouse_warping none
floating_modifier $mod normal

workspace_layout default

client.focused          #c4a7e7 #191724 #e0def4 #9ccfd8 #c4a7e7
client.focused_inactive  #393552 #191724 #908caa #393552 #393552
client.unfocused         #26233a #191724 #908caa #26233a #26233a
client.urgent            #eb6f92 #191724 #e0def4 #eb6f92 #eb6f92
client.placeholder       #393552 #191724 #908caa #393552 #393552
client.background        #191724

seat * xcursor_theme Bibata-Modern-Ice 24
