input type:keyboard {
    xkb_layout "us"
}

input type:touchpad {
    tap enabled
    drag enabled
    dwt enabled
    natural_scroll disabled
    left_handed disabled
    middle_emulation disabled
}

input type:pointer {
    pointer_accel 0
}
