bindsym $mod+Return exec kitty
bindsym $mod+b exec helium-browser
bindsym $mod+e exec dolphin
bindsym $mod+space exec ~/.config/rofi/launchers/launcher.sh
bindsym $mod+g exec kdenlive
bindsym $mod+n exec kitty nvim

bindsym $mod+v exec ~/.config/rofi/clipboard/clipboard.sh
bindsym $mod+Mod1+space exec ~/.config/sway/scripts/wallpaper-picker.sh
bindsym $mod+Mod1+l exec ~/.config/sway/scripts/lock.sh
